Repository OCA/maintainer-tools, pull requests merged in 2018-11, with the labels that each got.

#374 add "ready to merge" label
  tools/set_repo_labels.py
Labels: needs review

#392 Improve README
  README.md
Labels: approved, ready to merge

#396 Improve Odoo login method
  tools/github_login.py
  tools/odoo_login.py
Labels: needs review

#395 Most of the main branch bot has moved to oca-github-bot
  setup.py
  tools/main_branch_bot.py
Labels: approved, needs review

#397 [IMP] oca-gen-addon-readme : make organization name configurable and fix images URL
  template/module/readme/CONFIGURE.rst
  tools/gen_addon_readme.py
  tools/gen_addon_readme.template
Labels: approved
