Repository OCA/maintainer-tools, pull requests merged in 2019-09, with the labels that each got.

#425 Add a warning in readme for Alpha status
  tools/gen_addon_readme.py
  tools/gen_addon_readme.template
Labels: approved, ready to merge

#427 [FIX] 'preloadable = False' should not generate html readme
  tools/gen_addon_readme.py
Labels: approved

#422 [DEL] main branch bot moved to oca-github-bot
  setup.py
  tools/dist_to_simple_index.py
  tools/main_branch_bot.py
Labels: needs review

#421 [ADD] 'excludes' key in manifest file
  template/module/__manifest__.py
Labels: approved, ready to merge
